name: verteskt.github.io
markdown: kramdown

theme: jekyll-theme-cayman

prose:
  rooturl: "_posts"
  siteurl: "https://verteskt.github.io/"
  media: "_media"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          value: "CÃ­m"
      - name: "date"
        field:
          element: "hidden"
          value: CURRENT_DATETIME
      - name: "published"
        field:
          element: "hidden"
          value: "true"